/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': 'var(--color-primary)',
        'primary-light': 'var(--color-primary-light)',
        'primary-dark': 'var(--color-primary-dark)',
        'secondary': 'var(--color-secondary)',
        'accent': 'var(--color-accent)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'section-bg-lightest': 'var(--color-section-bg-lightest)',
        'section-bg-light': 'var(--color-section-bg-light)',
        'section-bg-lighter': 'var(--color-section-bg-lighter)',
        'header-gradient-start': 'var(--color-header-gradient-start)',
        'header-gradient-end': 'var(--color-header-gradient-end)',
        'dark': 'var(--color-dark)',
        'light': '#f9fafb', // Light background
        'gray-light': '#f3f4f6',
        'gray-medium': '#9ca3af',
        'gray-dark': '#4b5563',

        // Original colors (renamed for compatibility)
        'accent-orange': '#ff5a1f',
        'accent-red': '#e05252',
        'accent-red-bright': '#ef4444',
        'text-light': '#e5e7eb',
      },
      boxShadow: {
        'profile': '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'content': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'content-hover': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'contact': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'contact-hover': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'card': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'card-hover': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        'subtle': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      },
      animation: {
        'fadeIn': 'fadeIn 1s forwards',
        'scaleUp': 'scaleUp 0.6s ease-in-out forwards',
        'popUp': 'popUp 0.5s ease forwards',
        'fadeUp': 'fadeUp 1s ease-in-out',
        'slideUp': 'slideUp 1s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 2s infinite',
        'growWidth': 'growWidth 1.5s ease-out forwards',
        'gradient-slow': 'gradient 15s ease infinite',
        'blob': 'blob 7s infinite',
      },
      transitionProperty: {
        'transform': 'transform',
        'height': 'height',
        'spacing': 'margin, padding',
      },
      transformOrigin: {
        '3d': 'perspective(500px)',
      },
      borderWidth: {
        '5': '5px',
      },
      fontFamily: {
        'sans': ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'display': ['Poppins', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      backdropBlur: {
        'xs': '2px',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        gradient: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
      },
    },
  },
  safelist: [
    'animate-fadeIn',
    'animate-scaleUp',
    'animate-popUp',
    'animate-fadeUp',
    'animate-slideUp',
    'animate-float',
    'animate-pulse-slow',
    'animate-bounce-slow',
    'animate-growWidth',
    'animate-gradient-slow',
    'animate-blob',
    'animation-delay-2000',
    'animation-delay-4000',
    'opacity-0',
    'preserve-3d',
    'rotate-y-3',
    'rotate-x-2',
    'rotate-y-6',
    'rotate-x-3',
  ],
  plugins: [],
}